### ISSUE TITLE
Fix social preview image

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-javascript-docs#53]
We don't currently have a social preview image for the docs site

**Comment by karimStekelenburg** [comment]
@TimoGlastra, I'm not too familiar with this stuff but I did some Googleling. Is it correct that this is usually being done by `<meta>` tags?

**Comment by TimoGlastra** [comment]
Yes, I think we can use the demo as an example: https://github.com/animo/animo-demo/blob/main/client/public/index.html

**Comment by anagoessens** [comment]
![aries-social-preview](https://user-images.githubusercontent.com/22615213/177840065-53b70478-43bb-4fc1-a01f-25c1f6636c9c.png)

Something like this?

**Comment by anagoessens** [comment]
![aries-social-preview-layered](https://user-images.githubusercontent.com/22615213/177843540-11339572-b99d-43b3-ab36-a8bddf36edbd.png)

**Comment by anagoessens** [comment]
A.R.T.
