### ISSUE TITLE
[Bug]: Fix broken links in footer for Concepts and Tutorials

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-javascript-docs#87]
### Documentation Request

The footer links `Concepts` and `Tutorials` currently go to the 404 page.

### Version

0.2.x

### Which platform are you most interested in for documentation?

- [X] React Native
- [X] Node.JS

### Contribute (optional)

- [ ] Agree

**Comment by TimoGlastra** [comment]
@rapaktech maybe something you can pick up when you're back?

**Comment by rapaktech** [comment]
Yep
